# 55 Optode co-registration invariance

For each optode-cap subject we run the anonymization pipeline once via `run_pipeline` and pull two head-isolated meshes from the artifact bundle: `surface_ctf` (head-isolated, CTF frame, **before** face-mask deletion) and `surface_anon_ctf` (same head-isolated mesh, **after** face-mask deletion). `ColoredStickerProcessor` is then run on both, sticker centres are matched between the two runs by nearest neighbour, and per-optode Euclidean deviations are reported for both the raw sticker centres and the scalp-projected optode positions (sticker centre minus optode length along the surface normal).

Both inputs come from the same in-memory pipeline run and share the same head-isolation step, the same CTF alignment, and the same un-recompressed original texture; the only geometric difference between them is the set of vertices removed by `delete_masked_vertices`. This matters: comparing the raw Einstar OBJ (which includes neck, shoulders, and clothing) against the head-only anonymized output would let `ColoredStickerProcessor` pick up yellow false positives on the body, inflating the sticker count on the original side and producing nearest-neighbour matching artifacts when the unmatched phantoms get paired with real cap stickers on the opposite side of the head. Sharing head-isolation removes that confound.

**Cohort restriction.** This test detects yellow sticker markers mounted on the optode cap. Only the optode-cap cohort (S1--S7, Subject 16--22) carries those markers; the bare-cap cohort (S8--S11, Subject 12--15) wears a cap without optodes mounted, so the test is undefined for them and they are intentionally skipped here. The other evaluation notebooks (51, 52, 53, 54, 56, 59) iterate over the full eleven-subject cohort.

Populates Table 4.5 of the thesis (Section 4.4.3). Expected outcome: zero deviation up to numerical noise, because every sticker sits on the cap which lies above the cap-boundary plane and therefore outside the facial mask by construction.

Output: `thesis_results_out/coreg_invariance.csv`, with one row per optode-cap subject and an `optode=True` column for schema parity with the other Results-chapter CSVs.

In [1]:
import sys, pathlib
sys.path.insert(0, str(pathlib.Path().resolve()))
from _thesis_helpers import (
    OPTODE_SUBJECTS, subject_paths, load_raw, load_landmarks, run_pipeline,
    is_optode, s_id,
)

import numpy as np
import pandas as pd

OUT_DIR = pathlib.Path('thesis_results_out')
OUT_DIR.mkdir(exist_ok=True)

import cedalion
from cedalion.geometry.photogrammetry.processors import (
    ColoredStickerProcessor,
)
from scipy.spatial import KDTree

# Yellow optode stickers, same HSV range as notebook 41.
COLORS = {'O': (0.11, 0.21, 0.7, 1.0)}
OPTODE_LENGTH = 22.6 * cedalion.units.mm

## 1. Sticker detection wrapper

Returns sticker centres and normals as plain numpy arrays for easy nearest-neighbour matching.

In [2]:
def detect_stickers(surface):

    proc = ColoredStickerProcessor(colors=COLORS)

    centres, normals = proc.process(surface, details=False)

    c_np = centres.pint.dequantify().values

    n_np = normals.values if hasattr(normals, 'values') else np.asarray(normals)

    return c_np, n_np



def match_by_nn(a, b):

    '''For each row of a, return the index of the nearest row of b.'''

    tree = KDTree(b)

    _, idx = tree.query(a)

    return idx

## 2. Per-subject comparison

In [3]:
rows = []
for n in OPTODE_SUBJECTS:
    paths = subject_paths(n)
    if not paths.raw_exists:
        print(f'skipping Subject{n}: missing raw scan')
        continue
    if not paths.landmarks_exist:
        print(f'skipping Subject{n}: missing landmarks TSV')
        continue
    print(f'--- {s_id(n)} (Subject{n}) ---')

    art = run_pipeline(load_raw(n), load_landmarks(n), subject=n)
    surface_orig = art.surface_ctf       # head-isolated, CTF, before face deletion
    surface_anon = art.surface_anon_ctf  # head-isolated, CTF, after face deletion

    c_orig, n_orig = detect_stickers(surface_orig)
    c_anon, n_anon = detect_stickers(surface_anon)

    if len(c_orig) == 0 or len(c_anon) == 0:
        print(f'  no stickers detected on one side '
              f'(orig={len(c_orig)}, anon={len(c_anon)})')
        continue

    idx = match_by_nn(c_orig, c_anon)
    sticker_dev = np.linalg.norm(c_orig - c_anon[idx], axis=1)

    L = float(OPTODE_LENGTH.to('mm').magnitude)
    scalp_orig = c_orig - L * n_orig
    scalp_anon = c_anon[idx] - L * n_anon[idx]
    scalp_dev = np.linalg.norm(scalp_orig - scalp_anon, axis=1)

    rows.append({
        's_id': s_id(n),
        'subject': n,
        'optode': is_optode(n),
        'n_stickers_original': len(c_orig),
        'n_stickers_anonymized': len(c_anon),
        'n_matched': len(idx),
        'sticker_mean_mm': float(sticker_dev.mean()),
        'sticker_median_mm': float(np.median(sticker_dev)),
        'sticker_max_mm': float(sticker_dev.max()),
        'scalp_mean_mm': float(scalp_dev.mean()),
        'scalp_median_mm': float(np.median(scalp_dev)),
        'scalp_max_mm': float(scalp_dev.max()),
    })
    print(rows[-1])

--- S1 (Subject16) ---


[[ -18.00455171 -101.35689301  -49.90083092]
 [ -17.36425037 -101.26923325  -50.40896743]
 [ -17.58280801 -100.98613082  -51.14345664]
 ...
 [-118.10573076   39.40446198   33.01622935]
 [-121.2215538    33.19909023   55.6572317 ]
 [ -32.02600462   65.39815272  -46.98181825]]
[[-83.62772362 -39.18978661 122.40603235]
 [ 17.59523849 -41.4593695  154.15166116]
 [-75.93538423 -40.2388502  128.16637636]
 ...
 [  3.40884444 -80.66966494 132.99746232]
 [  2.96306468 -80.70235116 133.05590369]
 [  2.20979903 -80.741302   132.99769018]]
O (0.11, 0.21, 0.7, 1.0)
[0.80864561 0.25652499 0.90779208 0.99456393 0.88376101 0.63718142
 0.32089567 0.62904539 0.18573855 1.15660754 0.1536981  0.00922152
 0.56982297 0.64168943 0.46328306 0.61566801 0.87477079 0.15965823
 0.11353025]
3.574345116866262
surface.crs ctf


/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[ -18.00455171 -101.35689301  -49.90083092]
 [ -17.36425037 -101.26923325  -50.40896743]
 [ -17.58280801 -100.98613082  -51.14345664]
 ...
 [-118.10573076   39.40446198   33.01622935]
 [-121.2215538    33.19909023   55.6572317 ]
 [ -32.02600462   65.39815272  -46.98181825]]
[[-83.62772362 -39.18978661 122.40603235]
 [ 17.59523849 -41.4593695  154.15166116]
 [-75.93538423 -40.2388502  128.16637636]
 ...
 [  3.40884444 -80.66966494 132.99746232]
 [  2.96306468 -80.70235116 133.05590369]
 [  2.20979903 -80.741302   132.99769018]]
O (0.11, 0.21, 0.7, 1.0)
[0.80864561 0.25652499 0.90779208 0.99456393 0.88376101 0.63718142
 0.32089567 0.62904539 0.18573855 1.15660754 0.1536981  0.00922152
 0.56982297 0.64168943 0.46328306 0.61566801 0.87477079 0.15965823
 0.11353025]
3.574345116866262
surface.crs ctf
{'s_id': 'S1', 'subject': 16, 'optode': True, 'n_stickers_original': 19, 'n_stickers_anonymized': 19, 'n_matched': 19, 'sticker_mean_mm': 0.0, 'sticker_median_mm': 0.0, 'sticker_max_mm': 0.0, '

/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[  65.47687439  -80.28944467  102.15790986]
 [ -14.25586001  -97.02959146  129.51194087]
 [  65.60264033  -80.23268124  101.74600031]
 ...
 [-101.85769168  -61.24753227  -74.55462338]
 [  65.74948752   57.00264357    6.88285683]
 [-140.75885792   31.44224894   44.78839688]]
[[ -8.78941802 -97.18778783 128.87414346]
 [-12.90339337 -96.94155039 129.60341357]
 [  6.89436461 -61.96529606 164.88885885]
 ...
 [118.12166204  12.36751852  97.85099316]
 [117.8414076   12.21540588  98.13175854]
 [ 85.35057105  -9.56495843 138.81084171]]
O (0.11, 0.21, 0.7, 1.0)
[0.4250353  1.35472219 1.7145254  0.39138499 1.29862752 0.62320719
 0.38994548 0.61920156 0.78096456 0.49167592 1.33193309 0.74436605
 1.48520167 1.26870412 0.9219634  1.02609914 0.93732249 0.66719798
 0.08219981 1.76435313 0.45591146]
3.728244425455729
surface.crs ctf


/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[  65.47687439  -80.28944467  102.15790986]
 [ -14.25586001  -97.02959146  129.51194087]
 [  65.60264033  -80.23268124  101.74600031]
 ...
 [ 121.3275435    31.24442274   60.22199026]
 [-101.85769168  -61.24753227  -74.55462338]
 [-140.75885792   31.44224894   44.78839688]]
[[ -8.78941802 -97.18778783 128.87414346]
 [-12.90339337 -96.94155039 129.60341357]
 [  6.89436461 -61.96529606 164.88885885]
 ...
 [118.12166204  12.36751852  97.85099316]
 [117.8414076   12.21540588  98.13175854]
 [ 85.35057105  -9.56495843 138.81084171]]
O (0.11, 0.21, 0.7, 1.0)
[0.4250353  1.35472219 1.7145254  0.39138499 1.29862752 0.62320719
 0.38994548 0.61920156 0.78096456 0.49167592 1.33193309 0.74436605
 1.48520167 1.26870412 0.9219634  1.02609914 0.93732249 0.66719798
 0.08219981 1.76435313 0.45591146]
3.728244425455729
surface.crs ctf
{'s_id': 'S2', 'subject': 17, 'optode': True, 'n_stickers_original': 21, 'n_stickers_anonymized': 21, 'n_matched': 21, 'sticker_mean_mm': 0.0, 'sticker_median_mm': 0.0, 's

/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[-106.89851615  -70.1308133   -70.82280567]
 [  56.38923424   92.91160787  102.92696745]
 [-106.2895862   -72.28805001  -72.5463224 ]
 ...
 [ -95.6756615    34.38420012   87.4039566 ]
 [  29.34827461  -39.56182604  176.25640736]
 [ 123.24055366  -27.52003944  105.79146487]]
[[ -5.7246123  -22.62506125 189.12924634]
 [ 22.00280273  51.80537739 177.94232434]
 [ 64.99376762 -48.62151484 157.81970383]
 ...
 [103.57696231 -35.50472854 133.09734029]
 [103.72486955 -36.02476308 133.21046435]
 [103.72486955 -36.02476308 133.21046435]]
O (0.11, 0.21, 0.7, 1.0)
[0.0036689  0.50134591 0.33380898 0.01219627 0.32939292 0.4857357
 0.82973671 0.01969216 0.2087255  0.2573539  0.04424996 0.29603752
 0.0223481  0.66451438 0.01560234]
4.787072530110677
surface.crs ctf


/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[-106.89851615  -70.1308133   -70.82280567]
 [  56.38923424   92.91160787  102.92696745]
 [-106.2895862   -72.28805001  -72.5463224 ]
 ...
 [ -95.6756615    34.38420012   87.4039566 ]
 [  29.34827461  -39.56182604  176.25640736]
 [ 123.24055366  -27.52003944  105.79146487]]
[[ -5.7246123  -22.62506125 189.12924634]
 [ 22.00280273  51.80537739 177.94232434]
 [ 64.99376762 -48.62151484 157.81970383]
 ...
 [103.57696231 -35.50472854 133.09734029]
 [103.72486955 -36.02476308 133.21046435]
 [103.72486955 -36.02476308 133.21046435]]
O (0.11, 0.21, 0.7, 1.0)
[0.0036689  0.50134591 0.33380898 0.01219627 0.32939292 0.4857357
 0.82973671 0.01969216 0.2087255  0.2573539  0.04424996 0.29603752
 0.0223481  0.66451438 0.01560234]
4.787072530110677
surface.crs ctf
{'s_id': 'S3', 'subject': 18, 'optode': True, 'n_stickers_original': 15, 'n_stickers_anonymized': 15, 'n_matched': 15, 'sticker_mean_mm': 0.0, 'sticker_median_mm': 0.0, 'sticker_max_mm': 0.0, 'scalp_mean_mm': 0.0, 'scalp_median_mm': 0.0, '

/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[-113.8032046   -53.08784559   71.880547  ]
 [-103.29062417 -107.85004844  -32.35201183]
 [-103.29062417 -107.85004844  -32.35201183]
 ...
 [ 100.43871096   14.46711511  104.56603113]
 [  82.43728829   15.48113555  116.65876386]
 [-107.42457848   37.60107791  103.38792102]]
[[-59.52167162 -28.88690974 148.91521506]
 [-21.76927127 -34.07006931 159.61994357]
 [-20.19610435 -33.9221174  160.0461819 ]
 ...
 [ 58.37494006 -73.81710647 110.69145213]
 [ 58.5809957  -74.32448339 109.96314175]
 [ 68.21091598  15.3161636  136.88198099]]
O (0.11, 0.21, 0.7, 1.0)
[6.71425095e-01 3.86997147e-01 3.72543335e-04 1.97870560e-01
 1.28563614e-01 2.53142548e-02 8.16248322e-02 1.82085953e-01
 3.85536728e-01 1.22611160e-01 6.47010040e-02 8.18056488e-02]
4.740824508666992
surface.crs ctf


/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[-113.8032046   -53.08784559   71.880547  ]
 [-103.29062417 -107.85004844  -32.35201183]
 [-103.29062417 -107.85004844  -32.35201183]
 ...
 [ 100.43871096   14.46711511  104.56603113]
 [  82.43728829   15.48113555  116.65876386]
 [-107.42457848   37.60107791  103.38792102]]
[[-59.52167162 -28.88690974 148.91521506]
 [-21.76927127 -34.07006931 159.61994357]
 [-20.19610435 -33.9221174  160.0461819 ]
 ...
 [ 58.37494006 -73.81710647 110.69145213]
 [ 58.5809957  -74.32448339 109.96314175]
 [ 68.21091598  15.3161636  136.88198099]]
O (0.11, 0.21, 0.7, 1.0)
[6.71425095e-01 3.86997147e-01 3.72543335e-04 1.97870560e-01
 1.28563614e-01 2.53142548e-02 8.16248322e-02 1.82085953e-01
 3.85536728e-01 1.22611160e-01 6.47010040e-02 8.18056488e-02]
4.740824508666992
surface.crs ctf
{'s_id': 'S4', 'subject': 19, 'optode': True, 'n_stickers_original': 12, 'n_stickers_anonymized': 12, 'n_matched': 12, 'sticker_mean_mm': 0.0, 'sticker_median_mm': 0.0, 'sticker_max_mm': 0.0, 'scalp_mean_mm': 0.0, 'scalp_me

/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[ 35.09490112  97.86997705  58.73746878]
 [124.42990386 -12.84338861  34.03623991]
 [-50.33763433  71.28006033 -12.92168519]
 ...
 [ 37.12746749 -44.49309472 -97.35178634]
 [ 66.36687584  52.81750998  -0.22890506]
 [  5.91189222 -63.80639667  -4.57423419]]
[[ 85.22554372  56.91407849 106.68076901]
 [ 84.85429556  58.07530936 106.7336659 ]
 [ 96.85373711 -51.30071399  95.8984004 ]
 ...
 [ 46.89909955 -36.88837801 144.08351746]
 [-63.44282019  20.22921969 146.01425848]
 [-62.76267774  19.04888083 146.30842474]]
O (0.11, 0.21, 0.7, 1.0)
[0.86820599 0.10765149 0.90899731 0.27450031 1.61653851 0.90777484
 0.76742847 1.33904865 0.72180462 0.37066303 2.18605136 0.57905865
 0.28969311 0.75351697]
3.9659535544259206
surface.crs ctf


/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[  35.09490112   97.86997705   58.73746878]
 [ -50.33763433   71.28006033  -12.92168519]
 [ -49.89860383   71.73853994  -13.65070286]
 ...
 [ -68.89317405  -69.92407389   11.21823115]
 [  67.31874698  -33.53917681  131.16210718]
 [-100.39479522   30.51108057   79.42501198]]
[[ 85.22554372  56.91407849 106.68076901]
 [ 84.85429556  58.07530936 106.7336659 ]
 [ 96.85373711 -51.30071399  95.8984004 ]
 ...
 [ 46.89909955 -36.88837801 144.08351746]
 [-63.44282019  20.22921969 146.01425848]
 [-62.76267774  19.04888083 146.30842474]]
O (0.11, 0.21, 0.7, 1.0)
[0.86820599 0.10765149 0.90899731 0.27450031 1.61653851 0.90777484
 0.76742847 1.33904865 0.72180462 0.37066303 2.18605136 0.57905865
 0.28969311 0.75351697]
3.9659535544259206
surface.crs ctf
{'s_id': 'S5', 'subject': 20, 'optode': True, 'n_stickers_original': 14, 'n_stickers_anonymized': 14, 'n_matched': 14, 'sticker_mean_mm': 0.0, 'sticker_median_mm': 0.0, 'sticker_max_mm': 0.0, 'scalp_mean_mm': 0.0, 'scalp_median_mm': 0.0, 'scalp_max

/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[ -98.21786352  -62.38812396   41.79815346]
 [ -98.21786352  -62.38812396   41.79815346]
 [  52.06200437  -79.95807643  -66.5228363 ]
 ...
 [ -87.18138387  -69.12245406   80.19120617]
 [-112.706133     52.8127399     8.5877967 ]
 [  62.71977626  -70.57026629  114.33969776]]
[[ 79.17420395 -28.3690041  132.96956622]
 [ 79.52020588 -28.25672806 132.77876652]
 [ 44.92299859 -38.88175864 149.44010499]
 ...
 [ 52.98484562 -75.0239397  121.30531568]
 [ 53.32444995 -74.90489972 121.09738209]
 [ 53.76517041 -74.88413279 120.65575182]]
O (0.11, 0.21, 0.7, 1.0)
[1.02256741 0.62184085 1.11265652 0.77421261 0.35396762 0.39553592
 0.55003391 0.06770206 0.24637607 0.2069968  2.20248623 0.52835575
 0.22509708 1.07742191 0.74048672 0.28563229 0.50002017 0.54005405
 0.82463962]
3.8092629683645156
surface.crs ctf


/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[ -98.21786352  -62.38812396   41.79815346]
 [ -98.21786352  -62.38812396   41.79815346]
 [ -98.32550234  -62.38307666   41.40694087]
 ...
 [ -87.18138387  -69.12245406   80.19120617]
 [-112.706133     52.8127399     8.5877967 ]
 [  62.71977626  -70.57026629  114.33969776]]
[[ 79.17420395 -28.3690041  132.96956622]
 [ 79.52020588 -28.25672806 132.77876652]
 [ 44.92299859 -38.88175864 149.44010499]
 ...
 [ 52.98484562 -75.0239397  121.30531568]
 [ 53.32444995 -74.90489972 121.09738209]
 [ 53.76517041 -74.88413279 120.65575182]]
O (0.11, 0.21, 0.7, 1.0)
[1.02256741 0.62184085 1.11265652 0.77421261 0.35396762 0.39553592
 0.55003391 0.06770206 0.24637607 0.2069968  2.20248623 0.52835575
 0.22509708 1.07742191 0.74048672 0.28563229 0.50002017 0.54005405
 0.82463962]
3.8092629683645156
surface.crs ctf
{'s_id': 'S6', 'subject': 21, 'optode': True, 'n_stickers_original': 19, 'n_stickers_anonymized': 19, 'n_matched': 19, 'sticker_mean_mm': 0.0, 'sticker_median_mm': 0.0, 'sticker_max_mm': 0.0, 

/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[-105.74027664 -103.51566261  -61.31412435]
 [ -29.30742122   99.47352464   70.94195514]
 [ -92.42476339  -10.48506195  125.02474163]
 ...
 [  13.18290011   14.93265513  133.13134391]
 [-100.37320932   10.39548131  110.67392679]
 [-120.62717017  -56.90471638  -14.17351366]]
[[ 50.88536149 -33.05322285 132.2957552 ]
 [  6.88961332 100.94044927  74.83482891]
 [  6.98656925 100.8354989   75.20945163]
 ...
 [114.29429785  38.9490919   64.82357339]
 [114.47327892  39.0640598   64.3823771 ]
 [114.28826933  39.31171899  63.21836039]]
O (0.11, 0.21, 0.7, 1.0)
[0.12055334 1.16284857 1.48791388 0.51091437 1.39303198 0.23838312
 0.4098559  0.28923456 0.3477276  1.51396856 1.61867151 0.49111139
 0.20229273 0.39042139 0.82300073 1.38996161 0.44898889 0.33806708
 0.17742365 0.22163885 0.2498382  0.53088983 0.27922052 0.13616846
 0.3668017  0.82408899 0.33818201 0.26384039 0.36703333 0.89757593
 1.02417181]
4.128625242171749
surface.crs ctf


/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


[[-105.74027664 -103.51566261  -61.31412435]
 [ -29.30742122   99.47352464   70.94195514]
 [ -92.42476339  -10.48506195  125.02474163]
 ...
 [  13.18290011   14.93265513  133.13134391]
 [-100.37320932   10.39548131  110.67392679]
 [-120.62717017  -56.90471638  -14.17351366]]
[[ 50.88536149 -33.05322285 132.2957552 ]
 [  6.88961332 100.94044927  74.83482891]
 [  6.98656925 100.8354989   75.20945163]
 ...
 [114.29429785  38.9490919   64.82357339]
 [114.47327892  39.0640598   64.3823771 ]
 [114.28826933  39.31171899  63.21836039]]
O (0.11, 0.21, 0.7, 1.0)
[0.12055334 1.16284857 1.48791388 0.51091437 1.39303198 0.23838312
 0.4098559  0.28923456 0.3477276  1.51396856 1.61867151 0.49111139
 0.20229273 0.39042139 0.82300073 1.38996161 0.44898889 0.33806708
 0.17742365 0.22163885 0.2498382  0.53088983 0.27922052 0.13616846
 0.3668017  0.82408899 0.33818201 0.26384039 0.36703333 0.89757593
 1.02417181]
4.128625242171749
surface.crs ctf
{'s_id': 'S7', 'subject': 22, 'optode': True, 'n_stickers_o

/home/ma7/.conda/envs/cedalion/lib/python3.11/site-packages/xarray/core/variable.py:315: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  data = np.asarray(data)


## 3. Summary

In [4]:
df = pd.DataFrame(rows)
# Order rows by S-ID (S1..S7) -- helper-controlled, matches thesis tables.
df = df.iloc[df['s_id'].map(lambda s: int(s[1:])).argsort()].reset_index(drop=True)
df

,s_id,subject,optode,n_stickers_original,n_stickers_anonymized,n_matched,sticker_mean_mm,sticker_median_mm,sticker_max_mm,scalp_mean_mm,scalp_median_mm,scalp_max_mm
0,S1,16,True,19,19,19,0.0,0.0,0.0,0.0,0.0,0.0
1,S2,17,True,21,21,21,0.0,0.0,0.0,0.0,0.0,0.0
2,S3,18,True,15,15,15,0.0,0.0,0.0,0.0,0.0,0.0
3,S4,19,True,12,12,12,0.0,0.0,0.0,0.0,0.0,0.0
4,S5,20,True,14,14,14,0.0,0.0,0.0,0.0,0.0,0.0
5,S6,21,True,19,19,19,0.0,0.0,0.0,0.0,0.0,0.0
6,S7,22,True,31,31,31,0.0,0.0,0.0,0.0,0.0,0.0


## 4. Save

In [5]:
out = OUT_DIR / 'coreg_invariance.csv'

df.to_csv(out, index=False)

print(f'Wrote {out}')

Wrote thesis_results_out/coreg_invariance.csv
